[package]
name = "sat-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
pretty_env_logger = "0.5.0"
rand = "0.8.5"
rayon = "1.8.1"

[dev-dependencies]
criterion = {version="0.5.1",features=["html_reports"]}

[[bench]]
name="satlib"
harness=false